language: node_js

#node_js:
#  - "7"
#  - "6"
#  - "stable"

matrix:
  include:
    - os: linux
      node_js: "8"
    - os: linux
      node_js: "7"
    - os: linux
      node_js: "6"
    - os: linux
      node_js: "4.3"
#    - os: osx
#      node_js: "8"
#    - os: osx
#      node_js: "7"

before_script:
  - cd react
  - yarn
  - npm run devtest

script:
  - cd ..
  - export WEBPACK_MODE=dev
  - echo $WEBPACK_MODE
  - npm run test
  - cd react
  - npm run prod
  - cd ..
  - rm -rf docs/dist/*
  - export WEBPACK_MODE=prod
  - echo $WEBPACK_MODE
  - npm run test

